name: Reset Agenda

on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar al endpoint de reset
        run: curl -X POST https://agenda-de-directos.onrender.com/reset

